//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTest.Cons.Meereen {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://temp.meereen.ddns.net/Meereen", ConfigurationName="Meereen.bookPortType")]
    public interface bookPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:Meereen) of message bookMsgRequest does not match the default value (http://temp.meereen.ddns.net/Meereen)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Meereen#bookMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebServiceTest.Cons.Meereen.bookMsgResponse bookMsg(WebServiceTest.Cons.Meereen.bookMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Meereen#bookMsg", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTest.Cons.Meereen.bookMsgResponse> bookMsgAsync(WebServiceTest.Cons.Meereen.bookMsgRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bookMsg", WrapperNamespace="urn:Meereen", IsWrapped=true)]
    public partial class bookMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string message_from_raven;
        
        public bookMsgRequest() {
        }
        
        public bookMsgRequest(string message_from_raven) {
            this.message_from_raven = message_from_raven;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bookMsgResponse", WrapperNamespace="urn:Meereen", IsWrapped=true)]
    public partial class bookMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public bookMsgResponse() {
        }
        
        public bookMsgResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface bookPortTypeChannel : WebServiceTest.Cons.Meereen.bookPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class bookPortTypeClient : System.ServiceModel.ClientBase<WebServiceTest.Cons.Meereen.bookPortType>, WebServiceTest.Cons.Meereen.bookPortType {
        
        public bookPortTypeClient() {
        }
        
        public bookPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public bookPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bookPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bookPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTest.Cons.Meereen.bookMsgResponse WebServiceTest.Cons.Meereen.bookPortType.bookMsg(WebServiceTest.Cons.Meereen.bookMsgRequest request) {
            return base.Channel.bookMsg(request);
        }
        
        public string bookMsg(string message_from_raven) {
            WebServiceTest.Cons.Meereen.bookMsgRequest inValue = new WebServiceTest.Cons.Meereen.bookMsgRequest();
            inValue.message_from_raven = message_from_raven;
            WebServiceTest.Cons.Meereen.bookMsgResponse retVal = ((WebServiceTest.Cons.Meereen.bookPortType)(this)).bookMsg(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTest.Cons.Meereen.bookMsgResponse> WebServiceTest.Cons.Meereen.bookPortType.bookMsgAsync(WebServiceTest.Cons.Meereen.bookMsgRequest request) {
            return base.Channel.bookMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTest.Cons.Meereen.bookMsgResponse> bookMsgAsync(string message_from_raven) {
            WebServiceTest.Cons.Meereen.bookMsgRequest inValue = new WebServiceTest.Cons.Meereen.bookMsgRequest();
            inValue.message_from_raven = message_from_raven;
            return ((WebServiceTest.Cons.Meereen.bookPortType)(this)).bookMsgAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://temp.meereen.ddns.net/Meereen", ConfigurationName="Meereen.getRavenResponsePortType")]
    public interface getRavenResponsePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:Meereen) of message getRavenResponseRequest does not match the default value (http://temp.meereen.ddns.net/Meereen)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Meereen#getRavenResponse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebServiceTest.Cons.Meereen.getRavenResponseResponse getRavenResponse(WebServiceTest.Cons.Meereen.getRavenResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Meereen#getRavenResponse", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTest.Cons.Meereen.getRavenResponseResponse> getRavenResponseAsync(WebServiceTest.Cons.Meereen.getRavenResponseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRavenResponse", WrapperNamespace="urn:Meereen", IsWrapped=true)]
    public partial class getRavenResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ravenID;
        
        public getRavenResponseRequest() {
        }
        
        public getRavenResponseRequest(int ravenID) {
            this.ravenID = ravenID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRavenResponseResponse", WrapperNamespace="urn:Meereen", IsWrapped=true)]
    public partial class getRavenResponseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public getRavenResponseResponse() {
        }
        
        public getRavenResponseResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface getRavenResponsePortTypeChannel : WebServiceTest.Cons.Meereen.getRavenResponsePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getRavenResponsePortTypeClient : System.ServiceModel.ClientBase<WebServiceTest.Cons.Meereen.getRavenResponsePortType>, WebServiceTest.Cons.Meereen.getRavenResponsePortType {
        
        public getRavenResponsePortTypeClient() {
        }
        
        public getRavenResponsePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public getRavenResponsePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getRavenResponsePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getRavenResponsePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTest.Cons.Meereen.getRavenResponseResponse WebServiceTest.Cons.Meereen.getRavenResponsePortType.getRavenResponse(WebServiceTest.Cons.Meereen.getRavenResponseRequest request) {
            return base.Channel.getRavenResponse(request);
        }
        
        public string getRavenResponse(int ravenID) {
            WebServiceTest.Cons.Meereen.getRavenResponseRequest inValue = new WebServiceTest.Cons.Meereen.getRavenResponseRequest();
            inValue.ravenID = ravenID;
            WebServiceTest.Cons.Meereen.getRavenResponseResponse retVal = ((WebServiceTest.Cons.Meereen.getRavenResponsePortType)(this)).getRavenResponse(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTest.Cons.Meereen.getRavenResponseResponse> WebServiceTest.Cons.Meereen.getRavenResponsePortType.getRavenResponseAsync(WebServiceTest.Cons.Meereen.getRavenResponseRequest request) {
            return base.Channel.getRavenResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTest.Cons.Meereen.getRavenResponseResponse> getRavenResponseAsync(int ravenID) {
            WebServiceTest.Cons.Meereen.getRavenResponseRequest inValue = new WebServiceTest.Cons.Meereen.getRavenResponseRequest();
            inValue.ravenID = ravenID;
            return ((WebServiceTest.Cons.Meereen.getRavenResponsePortType)(this)).getRavenResponseAsync(inValue);
        }
    }
}
