//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTest.Cons.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://temp.gartendigital.ddns:8080/Math", ConfigurationName="ServiceReference1.addPortType")]
    public interface addPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:Math) of message addRequest does not match the default value (http://temp.gartendigital.ddns:8080/Math)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Math#add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebServiceTest.Cons.ServiceReference1.addResponse add(WebServiceTest.Cons.ServiceReference1.addRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="urn:Math", IsWrapped=true)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public addRequest() {
        }
        
        public addRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="urn:Math", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Result;
        
        public addResponse() {
        }
        
        public addResponse(int Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface addPortTypeChannel : WebServiceTest.Cons.ServiceReference1.addPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addPortTypeClient : System.ServiceModel.ClientBase<WebServiceTest.Cons.ServiceReference1.addPortType>, WebServiceTest.Cons.ServiceReference1.addPortType {
        
        public addPortTypeClient() {
        }
        
        public addPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public addPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTest.Cons.ServiceReference1.addResponse WebServiceTest.Cons.ServiceReference1.addPortType.add(WebServiceTest.Cons.ServiceReference1.addRequest request) {
            return base.Channel.add(request);
        }
        
        public int add(int a, int b) {
            WebServiceTest.Cons.ServiceReference1.addRequest inValue = new WebServiceTest.Cons.ServiceReference1.addRequest();
            inValue.a = a;
            inValue.b = b;
            WebServiceTest.Cons.ServiceReference1.addResponse retVal = ((WebServiceTest.Cons.ServiceReference1.addPortType)(this)).add(inValue);
            return retVal.Result;
        }
    }
}
