//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTest.Cons.Mereen {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://temp.gartendigital.ddns:8080/Mereen", ConfigurationName="Mereen.bookPortType")]
    public interface bookPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:Mereen) of message bookMsgRequest does not match the default value (http://temp.gartendigital.ddns:8080/Mereen)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mereen#bookMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebServiceTest.Cons.Mereen.bookMsgResponse bookMsg(WebServiceTest.Cons.Mereen.bookMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mereen#bookMsg", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTest.Cons.Mereen.bookMsgResponse> bookMsgAsync(WebServiceTest.Cons.Mereen.bookMsgRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bookMsg", WrapperNamespace="urn:Mereen", IsWrapped=true)]
    public partial class bookMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string message_from_raven;
        
        public bookMsgRequest() {
        }
        
        public bookMsgRequest(string message_from_raven) {
            this.message_from_raven = message_from_raven;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bookMsgResponse", WrapperNamespace="urn:Mereen", IsWrapped=true)]
    public partial class bookMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public bookMsgResponse() {
        }
        
        public bookMsgResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface bookPortTypeChannel : WebServiceTest.Cons.Mereen.bookPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class bookPortTypeClient : System.ServiceModel.ClientBase<WebServiceTest.Cons.Mereen.bookPortType>, WebServiceTest.Cons.Mereen.bookPortType {
        
        public bookPortTypeClient() {
        }
        
        public bookPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public bookPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bookPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bookPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTest.Cons.Mereen.bookMsgResponse WebServiceTest.Cons.Mereen.bookPortType.bookMsg(WebServiceTest.Cons.Mereen.bookMsgRequest request) {
            return base.Channel.bookMsg(request);
        }
        
        public string bookMsg(string message_from_raven) {
            WebServiceTest.Cons.Mereen.bookMsgRequest inValue = new WebServiceTest.Cons.Mereen.bookMsgRequest();
            inValue.message_from_raven = message_from_raven;
            WebServiceTest.Cons.Mereen.bookMsgResponse retVal = ((WebServiceTest.Cons.Mereen.bookPortType)(this)).bookMsg(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTest.Cons.Mereen.bookMsgResponse> WebServiceTest.Cons.Mereen.bookPortType.bookMsgAsync(WebServiceTest.Cons.Mereen.bookMsgRequest request) {
            return base.Channel.bookMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTest.Cons.Mereen.bookMsgResponse> bookMsgAsync(string message_from_raven) {
            WebServiceTest.Cons.Mereen.bookMsgRequest inValue = new WebServiceTest.Cons.Mereen.bookMsgRequest();
            inValue.message_from_raven = message_from_raven;
            return ((WebServiceTest.Cons.Mereen.bookPortType)(this)).bookMsgAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://temp.gartendigital.ddns:8080/Mereen", ConfigurationName="Mereen.getRavenResponsePortType")]
    public interface getRavenResponsePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:Mereen) of message getRavenResponseRequest does not match the default value (http://temp.gartendigital.ddns:8080/Mereen)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mereen#getRavenResponse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebServiceTest.Cons.Mereen.getRavenResponseResponse getRavenResponse(WebServiceTest.Cons.Mereen.getRavenResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mereen#getRavenResponse", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTest.Cons.Mereen.getRavenResponseResponse> getRavenResponseAsync(WebServiceTest.Cons.Mereen.getRavenResponseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRavenResponse", WrapperNamespace="urn:Mereen", IsWrapped=true)]
    public partial class getRavenResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ravenID;
        
        public getRavenResponseRequest() {
        }
        
        public getRavenResponseRequest(int ravenID) {
            this.ravenID = ravenID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRavenResponseResponse", WrapperNamespace="urn:Mereen", IsWrapped=true)]
    public partial class getRavenResponseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public getRavenResponseResponse() {
        }
        
        public getRavenResponseResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface getRavenResponsePortTypeChannel : WebServiceTest.Cons.Mereen.getRavenResponsePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getRavenResponsePortTypeClient : System.ServiceModel.ClientBase<WebServiceTest.Cons.Mereen.getRavenResponsePortType>, WebServiceTest.Cons.Mereen.getRavenResponsePortType {
        
        public getRavenResponsePortTypeClient() {
        }
        
        public getRavenResponsePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public getRavenResponsePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getRavenResponsePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getRavenResponsePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTest.Cons.Mereen.getRavenResponseResponse WebServiceTest.Cons.Mereen.getRavenResponsePortType.getRavenResponse(WebServiceTest.Cons.Mereen.getRavenResponseRequest request) {
            return base.Channel.getRavenResponse(request);
        }
        
        public string getRavenResponse(int ravenID) {
            WebServiceTest.Cons.Mereen.getRavenResponseRequest inValue = new WebServiceTest.Cons.Mereen.getRavenResponseRequest();
            inValue.ravenID = ravenID;
            WebServiceTest.Cons.Mereen.getRavenResponseResponse retVal = ((WebServiceTest.Cons.Mereen.getRavenResponsePortType)(this)).getRavenResponse(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTest.Cons.Mereen.getRavenResponseResponse> WebServiceTest.Cons.Mereen.getRavenResponsePortType.getRavenResponseAsync(WebServiceTest.Cons.Mereen.getRavenResponseRequest request) {
            return base.Channel.getRavenResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTest.Cons.Mereen.getRavenResponseResponse> getRavenResponseAsync(int ravenID) {
            WebServiceTest.Cons.Mereen.getRavenResponseRequest inValue = new WebServiceTest.Cons.Mereen.getRavenResponseRequest();
            inValue.ravenID = ravenID;
            return ((WebServiceTest.Cons.Mereen.getRavenResponsePortType)(this)).getRavenResponseAsync(inValue);
        }
    }
}
